[package]
name = "couchbase-shell"
version = "0.5.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
edition = "2018"
default-run = "cbsh"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"
structopt = "0.3"
futures = "0.3"
http = "0.2"
warp = "0.2"
reqwest = { version = "0.11", features = ["json"] }
toml = "0.5"
dirs = "2.0"
rust-embed = "5.5"
mime_guess = "2.0"
rpassword = "4.0"
url = "2.1"
async-stream = "0.2"
regex = "1.3.7"
num-bigint = "0.3"
ansi_term = "0.12"
humantime-serde = "1.0"
log4rs = "1.0.0"
lazy_static = "1.4.0"

nu = { branch = "main",  git = "https://github.com/couchbaselabs/nushell.git", features = ["extra"] }
nu-protocol = { branch = "main", git = "https://github.com/couchbaselabs/nushell.git"  }
nu-errors = { branch = "main", git = "https://github.com/couchbaselabs/nushell.git"  }
nu-source = { branch = "main", git = "https://github.com/couchbaselabs/nushell.git" }
nu-cli = { branch = "main", git = "https://github.com/couchbaselabs/nushell.git" }
nu-engine = { branch = "main", git = "https://github.com/couchbaselabs/nushell.git" }

async-trait = "0.1.31"
serde = "1.0"
serde_json = "1.0"

tera = "1.1"
fake = { version = "2.2", features = ["chrono"] }
uuid = { version = "0.8", features = ["v4"] }
chrono = { version = "0.4.11", features = ["serde"] }

tokio = { version = "1", features = ["full"] }
surf = { version = "2.2.0", features = ["hyper-client"] }
base64 = "0.13.0"

[dev-dependencies]
nu-test-support = "0.18.1"
dunce = "1.0.1"
lazy_static = "1.4.0"

[[bin]]
name = "cbsh"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
doc=false
name="runtests"
path="tests/bin/mod.rs"
